version: "3.7"
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.web.yml
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
    volumes: ['./:/web']
  worker:
    build:
      context: ./
      dockerfile: ./Dockerfile.celery.yml
    command: celery -A api.standalone:celery_app worker -l info
    depends_on:
      - redis
    volumes: ['./:/celery']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

