
FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 5000
ENV DEBUG true

COPY . /web
WORKDIR /web



RUN apt-get update -y
RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6

RUN pip install  -r requirements.txt

EXPOSE 5000

#RUN pip install gunicorn

#CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "api/standalone:app"]
CMD ["python", "api/standalone.py"]
