FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime


ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0

COPY . /worker
WORKDIR /worker



RUN apt-get update -y
RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6


RUN pip install  -r requirements.txt
