model:
  name: model_clinical_basic
  params: 
    path: models/clinical/clinical_LSTM_traced.pth
    device: cpu
    # 'threshold'舍弃
dataset:
  name: dataset_clinical_basic
  params:
    root_dir: datasets/clinical

newdata_evals:
  -
    newdata_eval_name: eval_clinical_generalize
    newdata_eval_params: {}

algorithm:
  tests: 
  -
    name: algorithm_clinical_generalize
    params: 

      attack_types: 'white'
      attack_levels: 2
      w2v_path: models/clinical/w2v.npy
      word2id_path: models/clinical/word2id_v2.json
      id2word_path: models/clinical/id2word_v2.json
      word_neighbor_path: models/clinical/neighbor.json
      concept_path: models/clinical/concept.json
      label_num: 20
      output_dim: 20
