model:
  name: model_clinical_basic
  params: 
    path: models/clinical/clinical_LSTM_traced.pth
    device: cpu


dataset:
  name: dataset_clinical_basic
  params:
    root_dir: datasets/clinical

script: datasets/clinical_criteria.py