model:
  name: model_fundus_binary
  params: 
    path: model/jit_fundus_448.pth
    device: cpu
    output_type: logits
    threshold: 0.5
    multi2binary_indices:
      - 1
      - 2
      - 3
      - 4
dataset:
  name: dataset_fundus_binary
  params:
    root_dir: dataset/fundus.zip
    resize: 448

newdata_evals:
  -
    newdata_eval_name: eval_fundus
    newdata_eval_params: {}

algorithm:
  tests: 
  -
    name: algorithm_fundus_cyclegan
    params: 
      a_path: 'model/rc-upload-1644812599087-2-net_G_A.pth'
      b_path: 'model/rc-upload-1644812599087-5-net_G_B.pth'
#     name: algorithm_fundus_adv_pgd_pytorch
#     params: 
#       adv_level: 1