model:
  name: model_lungseg_basic
  params: 
    path: models/jit_lungseg_864.pth
    device: cpu
    threshold: 0.5

dataset:
  name: dataset_lungseg_basic
  params:
    root_dir: datasets/lung_seg
    resize: 864
#TODO:
script: datasets/lungseg_criteria.py