model:
  name: model_lungssd_basic
  params: 
    path: model/rc-upload-1641538858263-5-lung_ssd_jit.pth
    device: cpu
    # 模型参数路径变了
    size: 300
    # 新增size,为模型的输入尺寸
    num_classes: 2
    # 新增num_classes，为模型的目标检测数目加一
    device: 'cpu'
    # 'threshold'舍弃

dataset:
  name: dataset_lungssd_basic
  params:
    root_dir: dataset/rc-upload-1641538321222-2-test_dataset_lung_ssd_1.zip
    # 测试数据集的名称变了
    resize: 300
script: datasets/lungssd_criteria.py