model:
  name: model_lungseg_basic
  params: 
    path: models/jit_lungseg_864.pth
    device: cpu
    threshold: 0.5

dataset:
  name: dataset_lungseg_basic
  params:
    root_dir: datasets/lung_seg
    resize: 864

newdata_evals:
  -
    newdata_eval_name: eval_lungseg
    newdata_eval_params: {}

algorithm:
  tests: 
  -
    name: general_lungseg
    params: 
      attack_types: ['gaussian_blur']
      attack_levels: ['2']